# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  DOCKER_USERNAME: cwpearson
  IMAGE_NAME: azp-cuda-agent

stages:
- stage: "NUMA_Build"
  jobs:
  - job: "docker"
    strategy:
      matrix:
        amd64-ubuntu1604-cuda92:
          IMAGE_TAG: amd64-ubuntu1604-cuda92
        amd64-ubuntu1604-cuda100:
          IMAGE_TAG: amd64-ubuntu1604-cuda100
        amd64-ubuntu1604-cuda101:
          IMAGE_TAG: amd64-ubuntu1604-cuda101
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
    - script: |
        cd dockeragent
        docker build -f Dockerfile.$(IMAGE_TAG) -t $(DOCKER_USERNAME)/$(IMAGE_NAME):$(IMAGE_TAG) . 
      displayName: 'docker build'

    - script: |
        docker login -u $(DOCKER_USERNAME) -p $(DOCKER_PASSWORD)
      displayName: 'docker login'

    - script: |
        docker push $(DOCKER_USERNAME)/$(IMAGE_NAME)
      displayName: 'docker push'

    